[general]
import = [
  "~/.config/alacritty/custom_themes/gruvbox-dark.toml"
]
live_config_reload = true

[terminal]
shell = { program = "/usr/bin/zellij", args = [] }

[window]
opacity = 0.97

[font]
normal = { family = "NotoSansM Nerd Font Mono", style = "Regular" }
